### ISSUE TITLE
Port language: ruby

### ISSUE THREAD

**Issue by alexeyinkin** [akvelon/dart-highlighting#36]

**Comment by yescorp** [comment]
I found some bullshit...

In Circular JSON they have special char that is used to separate the path. (\~)
'\~contains\~1\~start\~variants\~0' 

They convert it to the radix16 String which results to be `'\x7e'`

<img width="506" alt="Screen Shot 2023-04-20 at 14 32 59" src="https://user-images.githubusercontent.com/79095619/233308327-34773ce5-b4ec-48a9-8dd3-b803355fa44f.png">

In Ruby, we have the regex with exact same combination `/\B\?\\(c|C-)[\x20-\x7e]/`.
That is why Circular JSON serializes it as ``/\B\?\\(c|C-)[\x20-\\x7e]/``.

<img width="492" alt="Screen Shot 2023-04-20 at 14 35 20" src="https://user-images.githubusercontent.com/79095619/233308938-0baff43a-7f59-4cfe-967a-bbbc7097bfc5.png">
